airbnb_dbt_snowflake_project:
  outputs:
    dev:
      account: 
      database: AIRBNB
      password: 
      role: ACCOUNTADMIN
      schema: dbt_schema
      threads: 1
      type: snowflake
      user: SANGITAKAR798
      warehouse: COMPUTE_WH
  target: dev
